/*
 * WoRMS REST webservice
 * The definitions and operations are listed below. Click on an operation name to view it's details, and test it.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.marinespecies.aphia.v1_0.handler.auth;

import org.marinespecies.aphia.v1_0.handler.Pair;

import java.util.Map;
import java.util.List;

/**
 * <p>ApiKeyAuth class.</p>
 *
 * @author mole
 * @version $Id: $Id
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-27T19:29:57.442Z[GMT]")public class ApiKeyAuth implements Authentication {
  private final String location;
  private final String paramName;

  private String apiKey;
  private String apiKeyPrefix;

  /**
   * <p>Constructor for ApiKeyAuth.</p>
   *
   * @param location a {@link java.lang.String} object.
   * @param paramName a {@link java.lang.String} object.
   */
  public ApiKeyAuth(String location, String paramName) {
    this.location = location;
    this.paramName = paramName;
  }

  /**
   * <p>Getter for the field <code>location</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getLocation() {
    return location;
  }

  /**
   * <p>Getter for the field <code>paramName</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getParamName() {
    return paramName;
  }

  /**
   * <p>Getter for the field <code>apiKey</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getApiKey() {
    return apiKey;
  }

  /**
   * <p>Setter for the field <code>apiKey</code>.</p>
   *
   * @param apiKey a {@link java.lang.String} object.
   */
  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  /**
   * <p>Getter for the field <code>apiKeyPrefix</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getApiKeyPrefix() {
    return apiKeyPrefix;
  }

  /**
   * <p>Setter for the field <code>apiKeyPrefix</code>.</p>
   *
   * @param apiKeyPrefix a {@link java.lang.String} object.
   */
  public void setApiKeyPrefix(String apiKeyPrefix) {
    this.apiKeyPrefix = apiKeyPrefix;
  }

  /** {@inheritDoc} */
  @Override
  public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams) {
    if (apiKey == null) {
      return;
    }
    String value;
    if (apiKeyPrefix != null) {
      value = apiKeyPrefix + " " + apiKey;
    } else {
      value = apiKey;
    }
    if ("query".equals(location)) {
      queryParams.add(new Pair(paramName, value));
    } else if ("header".equals(location)) {
      headerParams.put(paramName, value);
    }
  }
}
