/*
 * WoRMS REST webservice
 * The definitions and operations are listed below. Click on an operation name to view it's details, and test it.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.marinespecies.aphia.v1_0.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AphiaRecord
 *
 * @author mole
 * @version $Id: $Id
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-27T19:29:57.442Z[GMT]")
public class AphiaRecord {
  @SerializedName("AphiaID")
  private Integer aphiaID = 127160;

  @SerializedName("url")
  private String url = null;

  @SerializedName("scientificname")
  private String scientificname = null;

  @SerializedName("authority")
  private String authority = null;

  @SerializedName("taxonRankID")
  private Integer taxonRankID = null;

  @SerializedName("rank")
  private String rank = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("unacceptreason")
  private String unacceptreason = null;

  @SerializedName("valid_AphiaID")
  private Integer validAphiaID = null;

  @SerializedName("valid_name")
  private String validName = null;

  @SerializedName("valid_authority")
  private String validAuthority = null;

  @SerializedName("parentNameUsageID")
  private Integer parentNameUsageID = null;

  @SerializedName("kingdom")
  private String kingdom = null;

  @SerializedName("phylum")
  private String phylum = null;

  @SerializedName("class")
  private String propertyClass = null;

  @SerializedName("order")
  private String order = null;

  @SerializedName("family")
  private String family = null;

  @SerializedName("genus")
  private String genus = null;

  @SerializedName("citation")
  private String citation = null;

  @SerializedName("lsid")
  private String lsid = null;

  @SerializedName("isMarine")
  private Boolean isMarine = null;

  @SerializedName("isBrackish")
  private Boolean isBrackish = null;

  @SerializedName("isFreshwater")
  private Boolean isFreshwater = null;

  @SerializedName("isTerrestrial")
  private Boolean isTerrestrial = null;

  @SerializedName("isExtinct")
  private Boolean isExtinct = null;

  @SerializedName("match_type")
  private String matchType = null;

  @SerializedName("modified")
  private String modified = null;

  /**
   * <p>aphiaID.</p>
   *
   * @param aphiaID a {@link java.lang.Integer} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord aphiaID(Integer aphiaID) {
    this.aphiaID = aphiaID;
    return this;
  }

  /**
   * Unique and persistent identifier within WoRMS. Primary key in the database --
   *
   * @return aphiaID
   */
  @Schema(description = "Unique and persistent identifier within WoRMS. Primary key in the database -- ")
  public Integer getAphiaID() {
    return aphiaID;
  }

  /**
   * <p>Setter for the field <code>aphiaID</code>.</p>
   *
   * @param aphiaID a {@link java.lang.Integer} object.
   */
  public void setAphiaID(Integer aphiaID) {
    this.aphiaID = aphiaID;
  }

  /**
   * <p>url.</p>
   *
   * @param url a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord url(String url) {
    this.url = url;
    return this;
  }

  /**
   * HTTP URL to the AphiaRecord
   *
   * @return url
   */
  @Schema(description = "HTTP URL to the AphiaRecord")
  public String getUrl() {
    return url;
  }

  /**
   * <p>Setter for the field <code>url</code>.</p>
   *
   * @param url a {@link java.lang.String} object.
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * <p>scientificname.</p>
   *
   * @param scientificname a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord scientificname(String scientificname) {
    this.scientificname = scientificname;
    return this;
  }

  /**
   * the full scientific name without authorship
   *
   * @return scientificname
   */
  @Schema(description = "the full scientific name without authorship")
  public String getScientificname() {
    return scientificname;
  }

  /**
   * <p>Setter for the field <code>scientificname</code>.</p>
   *
   * @param scientificname a {@link java.lang.String} object.
   */
  public void setScientificname(String scientificname) {
    this.scientificname = scientificname;
  }

  /**
   * <p>authority.</p>
   *
   * @param authority a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord authority(String authority) {
    this.authority = authority;
    return this;
  }

  /**
   * the authorship information for the scientificname formatted according to the conventions of the applicable nomenclaturalCode
   *
   * @return authority
   */
  @Schema(description = "the authorship information for the scientificname formatted according to the conventions of the applicable nomenclaturalCode")
  public String getAuthority() {
    return authority;
  }

  /**
   * <p>Setter for the field <code>authority</code>.</p>
   *
   * @param authority a {@link java.lang.String} object.
   */
  public void setAuthority(String authority) {
    this.authority = authority;
  }

  /**
   * <p>taxonRankID.</p>
   *
   * @param taxonRankID a {@link java.lang.Integer} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord taxonRankID(Integer taxonRankID) {
    this.taxonRankID = taxonRankID;
    return this;
  }

  /**
   * the taxonomic rank identifier of the most specific name in the scientificname
   *
   * @return taxonRankID
   */
  @Schema(description = "the taxonomic rank identifier of the most specific name in the scientificname")
  public Integer getTaxonRankID() {
    return taxonRankID;
  }

  /**
   * <p>Setter for the field <code>taxonRankID</code>.</p>
   *
   * @param taxonRankID a {@link java.lang.Integer} object.
   */
  public void setTaxonRankID(Integer taxonRankID) {
    this.taxonRankID = taxonRankID;
  }

  /**
   * <p>rank.</p>
   *
   * @param rank a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord rank(String rank) {
    this.rank = rank;
    return this;
  }

  /**
   * the taxonomic rank of the most specific name in the scientificname
   *
   * @return rank
   */
  @Schema(description = "the taxonomic rank of the most specific name in the scientificname")
  public String getRank() {
    return rank;
  }

  /**
   * <p>Setter for the field <code>rank</code>.</p>
   *
   * @param rank a {@link java.lang.String} object.
   */
  public void setRank(String rank) {
    this.rank = rank;
  }

  /**
   * <p>status.</p>
   *
   * @param status a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord status(String status) {
    this.status = status;
    return this;
  }

  /**
   * the status of the use of the scientificname (usually a taxonomic opinion). Additional technical statuses are (1) &lt;u&gt;quarantined&lt;/u&gt;: hidden from public interface after decision from an editor and (2) &lt;u&gt;deleted&lt;/u&gt;: AphiaID should NOT be used anymore, please replace it by the valid_AphiaID
   *
   * @return status
   */
  @Schema(description = "the status of the use of the scientificname (usually a taxonomic opinion). Additional technical statuses are (1) <u>quarantined</u>: hidden from public interface after decision from an editor and (2) <u>deleted</u>: AphiaID should NOT be used anymore, please replace it by the valid_AphiaID")
  public String getStatus() {
    return status;
  }

  /**
   * <p>Setter for the field <code>status</code>.</p>
   *
   * @param status a {@link java.lang.String} object.
   */
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * <p>unacceptreason.</p>
   *
   * @param unacceptreason a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord unacceptreason(String unacceptreason) {
    this.unacceptreason = unacceptreason;
    return this;
  }

  /**
   * the reason why a scientificname is unaccepted
   *
   * @return unacceptreason
   */
  @Schema(description = "the reason why a scientificname is unaccepted")
  public String getUnacceptreason() {
    return unacceptreason;
  }

  /**
   * <p>Setter for the field <code>unacceptreason</code>.</p>
   *
   * @param unacceptreason a {@link java.lang.String} object.
   */
  public void setUnacceptreason(String unacceptreason) {
    this.unacceptreason = unacceptreason;
  }

  /**
   * <p>validAphiaID.</p>
   *
   * @param validAphiaID a {@link java.lang.Integer} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord validAphiaID(Integer validAphiaID) {
    this.validAphiaID = validAphiaID;
    return this;
  }

  /**
   * the AphiaID (for the scientificname) of the currently accepted taxon. NULL if there is no currently accepted taxon.
   *
   * @return validAphiaID
   */
  @Schema(description = "the AphiaID (for the scientificname) of the currently accepted taxon. NULL if there is no currently accepted taxon.")
  public Integer getValidAphiaID() {
    return validAphiaID;
  }

  /**
   * <p>Setter for the field <code>validAphiaID</code>.</p>
   *
   * @param validAphiaID a {@link java.lang.Integer} object.
   */
  public void setValidAphiaID(Integer validAphiaID) {
    this.validAphiaID = validAphiaID;
  }

  /**
   * <p>validName.</p>
   *
   * @param validName a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord validName(String validName) {
    this.validName = validName;
    return this;
  }

  /**
   * the scientificname of the currently accepted taxon
   *
   * @return validName
   */
  @Schema(description = "the scientificname of the currently accepted taxon")
  public String getValidName() {
    return validName;
  }

  /**
   * <p>Setter for the field <code>validName</code>.</p>
   *
   * @param validName a {@link java.lang.String} object.
   */
  public void setValidName(String validName) {
    this.validName = validName;
  }

  /**
   * <p>validAuthority.</p>
   *
   * @param validAuthority a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord validAuthority(String validAuthority) {
    this.validAuthority = validAuthority;
    return this;
  }

  /**
   * the authorship information for the scientificname of the currently accepted taxon
   *
   * @return validAuthority
   */
  @Schema(description = "the authorship information for the scientificname of the currently accepted taxon")
  public String getValidAuthority() {
    return validAuthority;
  }

  /**
   * <p>Setter for the field <code>validAuthority</code>.</p>
   *
   * @param validAuthority a {@link java.lang.String} object.
   */
  public void setValidAuthority(String validAuthority) {
    this.validAuthority = validAuthority;
  }

  /**
   * <p>parentNameUsageID.</p>
   *
   * @param parentNameUsageID a {@link java.lang.Integer} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord parentNameUsageID(Integer parentNameUsageID) {
    this.parentNameUsageID = parentNameUsageID;
    return this;
  }

  /**
   * the AphiaID (for the scientificname) of the direct, most proximate higher-rank parent taxon (in a classification)
   *
   * @return parentNameUsageID
   */
  @Schema(description = "the AphiaID (for the scientificname) of the direct, most proximate higher-rank parent taxon (in a classification)")
  public Integer getParentNameUsageID() {
    return parentNameUsageID;
  }

  /**
   * <p>Setter for the field <code>parentNameUsageID</code>.</p>
   *
   * @param parentNameUsageID a {@link java.lang.Integer} object.
   */
  public void setParentNameUsageID(Integer parentNameUsageID) {
    this.parentNameUsageID = parentNameUsageID;
  }

  /**
   * <p>kingdom.</p>
   *
   * @param kingdom a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord kingdom(String kingdom) {
    this.kingdom = kingdom;
    return this;
  }

  /**
   * the full scientific name of the kingdom in which the taxon is classified
   *
   * @return kingdom
   */
  @Schema(description = "the full scientific name of the kingdom in which the taxon is classified")
  public String getKingdom() {
    return kingdom;
  }

  /**
   * <p>Setter for the field <code>kingdom</code>.</p>
   *
   * @param kingdom a {@link java.lang.String} object.
   */
  public void setKingdom(String kingdom) {
    this.kingdom = kingdom;
  }

  /**
   * <p>phylum.</p>
   *
   * @param phylum a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord phylum(String phylum) {
    this.phylum = phylum;
    return this;
  }

  /**
   * the full scientific name of the phylum or division in which the taxon is classified
   *
   * @return phylum
   */
  @Schema(description = "the full scientific name of the phylum or division in which the taxon is classified")
  public String getPhylum() {
    return phylum;
  }

  /**
   * <p>Setter for the field <code>phylum</code>.</p>
   *
   * @param phylum a {@link java.lang.String} object.
   */
  public void setPhylum(String phylum) {
    this.phylum = phylum;
  }

  /**
   * <p>propertyClass.</p>
   *
   * @param propertyClass a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

  /**
   * the full scientific name of the class in which the taxon is classified
   *
   * @return propertyClass
   */
  @Schema(description = "the full scientific name of the class in which the taxon is classified")
  public String getPropertyClass() {
    return propertyClass;
  }

  /**
   * <p>Setter for the field <code>propertyClass</code>.</p>
   *
   * @param propertyClass a {@link java.lang.String} object.
   */
  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }

  /**
   * <p>order.</p>
   *
   * @param order a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord order(String order) {
    this.order = order;
    return this;
  }

  /**
   * the full scientific name of the order in which the taxon is classified
   *
   * @return order
   */
  @Schema(description = "the full scientific name of the order in which the taxon is classified")
  public String getOrder() {
    return order;
  }

  /**
   * <p>Setter for the field <code>order</code>.</p>
   *
   * @param order a {@link java.lang.String} object.
   */
  public void setOrder(String order) {
    this.order = order;
  }

  /**
   * <p>family.</p>
   *
   * @param family a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord family(String family) {
    this.family = family;
    return this;
  }

  /**
   * the full scientific name of the family in which the taxon is classified
   *
   * @return family
   */
  @Schema(description = "the full scientific name of the family in which the taxon is classified")
  public String getFamily() {
    return family;
  }

  /**
   * <p>Setter for the field <code>family</code>.</p>
   *
   * @param family a {@link java.lang.String} object.
   */
  public void setFamily(String family) {
    this.family = family;
  }

  /**
   * <p>genus.</p>
   *
   * @param genus a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord genus(String genus) {
    this.genus = genus;
    return this;
  }

  /**
   * the full scientific name of the genus in which the taxon is classified
   *
   * @return genus
   */
  @Schema(description = "the full scientific name of the genus in which the taxon is classified")
  public String getGenus() {
    return genus;
  }

  /**
   * <p>Setter for the field <code>genus</code>.</p>
   *
   * @param genus a {@link java.lang.String} object.
   */
  public void setGenus(String genus) {
    this.genus = genus;
  }

  /**
   * <p>citation.</p>
   *
   * @param citation a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord citation(String citation) {
    this.citation = citation;
    return this;
  }

  /**
   * a bibliographic reference for the resource as a statement indicating how this record should be cited (attributed) when used
   *
   * @return citation
   */
  @Schema(description = "a bibliographic reference for the resource as a statement indicating how this record should be cited (attributed) when used")
  public String getCitation() {
    return citation;
  }

  /**
   * <p>Setter for the field <code>citation</code>.</p>
   *
   * @param citation a {@link java.lang.String} object.
   */
  public void setCitation(String citation) {
    this.citation = citation;
  }

  /**
   * <p>lsid.</p>
   *
   * @param lsid a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord lsid(String lsid) {
    this.lsid = lsid;
    return this;
  }

  /**
   * LifeScience Identifier. Persistent GUID for an AphiaID
   *
   * @return lsid
   */
  @Schema(description = "LifeScience Identifier. Persistent GUID for an AphiaID")
  public String getLsid() {
    return lsid;
  }

  /**
   * <p>Setter for the field <code>lsid</code>.</p>
   *
   * @param lsid a {@link java.lang.String} object.
   */
  public void setLsid(String lsid) {
    this.lsid = lsid;
  }

  /**
   * <p>isMarine.</p>
   *
   * @param isMarine a {@link java.lang.Boolean} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord isMarine(Boolean isMarine) {
    this.isMarine = isMarine;
    return this;
  }

  /**
   * a boolean flag indicating whether the taxon is a marine organism, i.e. can be found in/above sea water. Possible values: 0/1/NULL
   *
   * @return isMarine
   */
  @Schema(description = "a boolean flag indicating whether the taxon is a marine organism, i.e. can be found in/above sea water. Possible values: 0/1/NULL")
  public Boolean isIsMarine() {
    return isMarine;
  }

  /**
   * <p>Setter for the field <code>isMarine</code>.</p>
   *
   * @param isMarine a {@link java.lang.Boolean} object.
   */
  public void setIsMarine(Boolean isMarine) {
    this.isMarine = isMarine;
  }

  /**
   * <p>isBrackish.</p>
   *
   * @param isBrackish a {@link java.lang.Boolean} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord isBrackish(Boolean isBrackish) {
    this.isBrackish = isBrackish;
    return this;
  }

  /**
   * a boolean flag indicating whether the taxon occurrs in brackish habitats. Possible values: 0/1/NULL
   *
   * @return isBrackish
   */
  @Schema(description = "a boolean flag indicating whether the taxon occurrs in brackish habitats. Possible values: 0/1/NULL")
  public Boolean isIsBrackish() {
    return isBrackish;
  }

  /**
   * <p>Setter for the field <code>isBrackish</code>.</p>
   *
   * @param isBrackish a {@link java.lang.Boolean} object.
   */
  public void setIsBrackish(Boolean isBrackish) {
    this.isBrackish = isBrackish;
  }

  /**
   * <p>isFreshwater.</p>
   *
   * @param isFreshwater a {@link java.lang.Boolean} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord isFreshwater(Boolean isFreshwater) {
    this.isFreshwater = isFreshwater;
    return this;
  }

  /**
   * a boolean flag indicating whether the taxon occurrs in freshwater habitats, i.e. can be found in/above rivers or lakes. Possible values: 0/1/NULL
   *
   * @return isFreshwater
   */
  @Schema(description = "a boolean flag indicating whether the taxon occurrs in freshwater habitats, i.e. can be found in/above rivers or lakes. Possible values: 0/1/NULL")
  public Boolean isIsFreshwater() {
    return isFreshwater;
  }

  /**
   * <p>Setter for the field <code>isFreshwater</code>.</p>
   *
   * @param isFreshwater a {@link java.lang.Boolean} object.
   */
  public void setIsFreshwater(Boolean isFreshwater) {
    this.isFreshwater = isFreshwater;
  }

  /**
   * <p>isTerrestrial.</p>
   *
   * @param isTerrestrial a {@link java.lang.Boolean} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord isTerrestrial(Boolean isTerrestrial) {
    this.isTerrestrial = isTerrestrial;
    return this;
  }

  /**
   * a boolean flag indicating the taxon is a terrestial organism, i.e. occurrs on land as opposed to the sea. Possible values: 0/1/NULL
   *
   * @return isTerrestrial
   */
  @Schema(description = "a boolean flag indicating the taxon is a terrestial organism, i.e. occurrs on land as opposed to the sea. Possible values: 0/1/NULL")
  public Boolean isIsTerrestrial() {
    return isTerrestrial;
  }

  /**
   * <p>Setter for the field <code>isTerrestrial</code>.</p>
   *
   * @param isTerrestrial a {@link java.lang.Boolean} object.
   */
  public void setIsTerrestrial(Boolean isTerrestrial) {
    this.isTerrestrial = isTerrestrial;
  }

  /**
   * <p>isExtinct.</p>
   *
   * @param isExtinct a {@link java.lang.Boolean} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord isExtinct(Boolean isExtinct) {
    this.isExtinct = isExtinct;
    return this;
  }

  /**
   * a flag indicating an extinct organism. Possible values: 0/1/NULL
   *
   * @return isExtinct
   */
  @Schema(description = "a flag indicating an extinct organism. Possible values: 0/1/NULL")
  public Boolean isIsExtinct() {
    return isExtinct;
  }

  /**
   * <p>Setter for the field <code>isExtinct</code>.</p>
   *
   * @param isExtinct a {@link java.lang.Boolean} object.
   */
  public void setIsExtinct(Boolean isExtinct) {
    this.isExtinct = isExtinct;
  }

  /**
   * <p>matchType.</p>
   *
   * @param matchType a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord matchType(String matchType) {
    this.matchType = matchType;
    return this;
  }

  /**
   * Type of match. Possible values: exact/like/phonetic/near_1/near_2
   *
   * @return matchType
   */
  @Schema(description = "Type of match. Possible values: exact/like/phonetic/near_1/near_2")
  public String getMatchType() {
    return matchType;
  }

  /**
   * <p>Setter for the field <code>matchType</code>.</p>
   *
   * @param matchType a {@link java.lang.String} object.
   */
  public void setMatchType(String matchType) {
    this.matchType = matchType;
  }

  /**
   * <p>modified.</p>
   *
   * @param modified a {@link java.lang.String} object.
   * @return a {@link org.marinespecies.aphia.v1_0.model.AphiaRecord} object.
   */
  public AphiaRecord modified(String modified) {
    this.modified = modified;
    return this;
  }

  /**
   * The most recent date-time in GMT on which the resource was changed
   *
   * @return modified
   */
  @Schema(description = "The most recent date-time in GMT on which the resource was changed")
  public String getModified() {
    return modified;
  }

  /**
   * <p>Setter for the field <code>modified</code>.</p>
   *
   * @param modified a {@link java.lang.String} object.
   */
  public void setModified(String modified) {
    this.modified = modified;
  }


  /** {@inheritDoc} */
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AphiaRecord aphiaRecord = (AphiaRecord) o;
    return Objects.equals(this.aphiaID, aphiaRecord.aphiaID) &&
        Objects.equals(this.url, aphiaRecord.url) &&
        Objects.equals(this.scientificname, aphiaRecord.scientificname) &&
        Objects.equals(this.authority, aphiaRecord.authority) &&
        Objects.equals(this.taxonRankID, aphiaRecord.taxonRankID) &&
        Objects.equals(this.rank, aphiaRecord.rank) &&
        Objects.equals(this.status, aphiaRecord.status) &&
        Objects.equals(this.unacceptreason, aphiaRecord.unacceptreason) &&
        Objects.equals(this.validAphiaID, aphiaRecord.validAphiaID) &&
        Objects.equals(this.validName, aphiaRecord.validName) &&
        Objects.equals(this.validAuthority, aphiaRecord.validAuthority) &&
        Objects.equals(this.parentNameUsageID, aphiaRecord.parentNameUsageID) &&
        Objects.equals(this.kingdom, aphiaRecord.kingdom) &&
        Objects.equals(this.phylum, aphiaRecord.phylum) &&
        Objects.equals(this.propertyClass, aphiaRecord.propertyClass) &&
        Objects.equals(this.order, aphiaRecord.order) &&
        Objects.equals(this.family, aphiaRecord.family) &&
        Objects.equals(this.genus, aphiaRecord.genus) &&
        Objects.equals(this.citation, aphiaRecord.citation) &&
        Objects.equals(this.lsid, aphiaRecord.lsid) &&
        Objects.equals(this.isMarine, aphiaRecord.isMarine) &&
        Objects.equals(this.isBrackish, aphiaRecord.isBrackish) &&
        Objects.equals(this.isFreshwater, aphiaRecord.isFreshwater) &&
        Objects.equals(this.isTerrestrial, aphiaRecord.isTerrestrial) &&
        Objects.equals(this.isExtinct, aphiaRecord.isExtinct) &&
        Objects.equals(this.matchType, aphiaRecord.matchType) &&
        Objects.equals(this.modified, aphiaRecord.modified);
  }

  /** {@inheritDoc} */
  @Override
  public int hashCode() {
    return Objects.hash(aphiaID, url, scientificname, authority, taxonRankID, rank, status, unacceptreason, validAphiaID, validName, validAuthority, parentNameUsageID, kingdom, phylum, propertyClass, order, family, genus, citation, lsid, isMarine, isBrackish, isFreshwater, isTerrestrial, isExtinct, matchType, modified);
  }


  /** {@inheritDoc} */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AphiaRecord {\n");
    
    sb.append("    aphiaID: ").append(toIndentedString(aphiaID)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    scientificname: ").append(toIndentedString(scientificname)).append("\n");
    sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
    sb.append("    taxonRankID: ").append(toIndentedString(taxonRankID)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    unacceptreason: ").append(toIndentedString(unacceptreason)).append("\n");
    sb.append("    validAphiaID: ").append(toIndentedString(validAphiaID)).append("\n");
    sb.append("    validName: ").append(toIndentedString(validName)).append("\n");
    sb.append("    validAuthority: ").append(toIndentedString(validAuthority)).append("\n");
    sb.append("    parentNameUsageID: ").append(toIndentedString(parentNameUsageID)).append("\n");
    sb.append("    kingdom: ").append(toIndentedString(kingdom)).append("\n");
    sb.append("    phylum: ").append(toIndentedString(phylum)).append("\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    genus: ").append(toIndentedString(genus)).append("\n");
    sb.append("    citation: ").append(toIndentedString(citation)).append("\n");
    sb.append("    lsid: ").append(toIndentedString(lsid)).append("\n");
    sb.append("    isMarine: ").append(toIndentedString(isMarine)).append("\n");
    sb.append("    isBrackish: ").append(toIndentedString(isBrackish)).append("\n");
    sb.append("    isFreshwater: ").append(toIndentedString(isFreshwater)).append("\n");
    sb.append("    isTerrestrial: ").append(toIndentedString(isTerrestrial)).append("\n");
    sb.append("    isExtinct: ").append(toIndentedString(isExtinct)).append("\n");
    sb.append("    matchType: ").append(toIndentedString(matchType)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
