/*
 * WoRMS REST webservice
 * The definitions and operations are listed below. Click on an operation name to view it's details, and test it.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.marinespecies.aphia.v1_0.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AphiaRank
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-28T23:57:28.350Z[GMT]")
public class AphiaRank {
  @JsonProperty("taxonRankID")
  private Integer taxonRankID = null;

  @JsonProperty("taxonRank")
  private String taxonRank = null;

  @JsonProperty("AphiaID")
  private Integer aphiaID = null;

  @JsonProperty("kingdom")
  private String kingdom = null;

  public AphiaRank taxonRankID(Integer taxonRankID) {
    this.taxonRankID = taxonRankID;
    return this;
  }

   /**
   * A taxonomic rank identifier
   * @return taxonRankID
  **/
  @Schema(example = "220", description = "A taxonomic rank identifier")
  public Integer getTaxonRankID() {
    return taxonRankID;
  }

  public void setTaxonRankID(Integer taxonRankID) {
    this.taxonRankID = taxonRankID;
  }

  public AphiaRank taxonRank(String taxonRank) {
    this.taxonRank = taxonRank;
    return this;
  }

   /**
   * A taxonomic rank name
   * @return taxonRank
  **/
  @Schema(example = "species", description = "A taxonomic rank name")
  public String getTaxonRank() {
    return taxonRank;
  }

  public void setTaxonRank(String taxonRank) {
    this.taxonRank = taxonRank;
  }

  public AphiaRank aphiaID(Integer aphiaID) {
    this.aphiaID = aphiaID;
    return this;
  }

   /**
   * AphiaID of the kingdom
   * @return aphiaID
  **/
  @Schema(example = "2", description = "AphiaID of the kingdom")
  public Integer getAphiaID() {
    return aphiaID;
  }

  public void setAphiaID(Integer aphiaID) {
    this.aphiaID = aphiaID;
  }

  public AphiaRank kingdom(String kingdom) {
    this.kingdom = kingdom;
    return this;
  }

   /**
   * The name of a taxonomic kingdom the rank is used in
   * @return kingdom
  **/
  @Schema(example = "Animalia", description = "The name of a taxonomic kingdom the rank is used in")
  public String getKingdom() {
    return kingdom;
  }

  public void setKingdom(String kingdom) {
    this.kingdom = kingdom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AphiaRank aphiaRank = (AphiaRank) o;
    return Objects.equals(this.taxonRankID, aphiaRank.taxonRankID) &&
        Objects.equals(this.taxonRank, aphiaRank.taxonRank) &&
        Objects.equals(this.aphiaID, aphiaRank.aphiaID) &&
        Objects.equals(this.kingdom, aphiaRank.kingdom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taxonRankID, taxonRank, aphiaID, kingdom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AphiaRank {\n");
    
    sb.append("    taxonRankID: ").append(toIndentedString(taxonRankID)).append("\n");
    sb.append("    taxonRank: ").append(toIndentedString(taxonRank)).append("\n");
    sb.append("    aphiaID: ").append(toIndentedString(aphiaID)).append("\n");
    sb.append("    kingdom: ").append(toIndentedString(kingdom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
