/*
 * WoRMS REST webservice
 * The definitions and operations are listed below. Click on an operation name to view it's details, and test it.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.marinespecies.aphia.v1_0.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.marinespecies.aphia.v1_0.model.AttributeValue;
/**
 * AttributeValue
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-28T23:57:28.350Z[GMT]")
public class AttributeValue {
  @JsonProperty("measurementValueID")
  private Integer measurementValueID = null;

  @JsonProperty("measurementValue")
  private String measurementValue = null;

  @JsonProperty("measurementValueCode")
  private String measurementValueCode = null;

  @JsonProperty("children")
  private List<AttributeValue> children = null;

  public AttributeValue measurementValueID(Integer measurementValueID) {
    this.measurementValueID = measurementValueID;
    return this;
  }

   /**
   * An identifier for facts stored in the column measurementValue
   * @return measurementValueID
  **/
  @Schema(example = "185", description = "An identifier for facts stored in the column measurementValue")
  public Integer getMeasurementValueID() {
    return measurementValueID;
  }

  public void setMeasurementValueID(Integer measurementValueID) {
    this.measurementValueID = measurementValueID;
  }

  public AttributeValue measurementValue(String measurementValue) {
    this.measurementValue = measurementValue;
    return this;
  }

   /**
   * The value of the measurement, fact, characteristic, or assertion
   * @return measurementValue
  **/
  @Schema(example = "macrobenthos", description = "The value of the measurement, fact, characteristic, or assertion")
  public String getMeasurementValue() {
    return measurementValue;
  }

  public void setMeasurementValue(String measurementValue) {
    this.measurementValue = measurementValue;
  }

  public AttributeValue measurementValueCode(String measurementValueCode) {
    this.measurementValueCode = measurementValueCode;
    return this;
  }

   /**
   * Additional info/code that helps to the describe/define the measurementValue
   * @return measurementValueCode
  **/
  @Schema(description = "Additional info/code that helps to the describe/define the measurementValue")
  public String getMeasurementValueCode() {
    return measurementValueCode;
  }

  public void setMeasurementValueCode(String measurementValueCode) {
    this.measurementValueCode = measurementValueCode;
  }

  public AttributeValue children(List<AttributeValue> children) {
    this.children = children;
    return this;
  }

  public AttributeValue addChildrenItem(AttributeValue childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<AttributeValue>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Child measurementValues that are more specific
   * @return children
  **/
  @Schema(description = "Child measurementValues that are more specific")
  public List<AttributeValue> getChildren() {
    return children;
  }

  public void setChildren(List<AttributeValue> children) {
    this.children = children;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttributeValue attributeValue = (AttributeValue) o;
    return Objects.equals(this.measurementValueID, attributeValue.measurementValueID) &&
        Objects.equals(this.measurementValue, attributeValue.measurementValue) &&
        Objects.equals(this.measurementValueCode, attributeValue.measurementValueCode) &&
        Objects.equals(this.children, attributeValue.children);
  }

  @Override
  public int hashCode() {
    return Objects.hash(measurementValueID, measurementValue, measurementValueCode, children);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttributeValue {\n");
    
    sb.append("    measurementValueID: ").append(toIndentedString(measurementValueID)).append("\n");
    sb.append("    measurementValue: ").append(toIndentedString(measurementValue)).append("\n");
    sb.append("    measurementValueCode: ").append(toIndentedString(measurementValueCode)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
