/*
 * IRMNG REST webservice
 * The definitions and operations are listed below. Click on an operation name to view it's details, and test it.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.irmng.aphia.v1_0.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.irmng.aphia.v1_0.model.Classification;
/**
 * Classification
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-09-09T18:22:45.022Z[GMT]")
public class Classification {
  @SerializedName("IRMNG_ID")
  private Integer IRMNG_ID = 126132;

  @SerializedName("rank")
  private String rank = null;

  @SerializedName("scientificname")
  private String scientificname = null;

  @SerializedName("child")
  private Classification child = null;

  public Classification IRMNG_ID(Integer IRMNG_ID) {
    this.IRMNG_ID = IRMNG_ID;
    return this;
  }

   /**
   * Get IRMNG_ID
   * @return IRMNG_ID
  **/
  @Schema(description = "")
  public Integer getIRMNGID() {
    return IRMNG_ID;
  }

  public void setIRMNGID(Integer IRMNG_ID) {
    this.IRMNG_ID = IRMNG_ID;
  }

  public Classification rank(String rank) {
    this.rank = rank;
    return this;
  }

   /**
   * Get rank
   * @return rank
  **/
  @Schema(description = "")
  public String getRank() {
    return rank;
  }

  public void setRank(String rank) {
    this.rank = rank;
  }

  public Classification scientificname(String scientificname) {
    this.scientificname = scientificname;
    return this;
  }

   /**
   * Get scientificname
   * @return scientificname
  **/
  @Schema(description = "")
  public String getScientificname() {
    return scientificname;
  }

  public void setScientificname(String scientificname) {
    this.scientificname = scientificname;
  }

  public Classification child(Classification child) {
    this.child = child;
    return this;
  }

   /**
   * Get child
   * @return child
  **/
  @Schema(description = "")
  public Classification getChild() {
    return child;
  }

  public void setChild(Classification child) {
    this.child = child;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Classification classification = (Classification) o;
    return Objects.equals(this.IRMNG_ID, classification.IRMNG_ID) &&
        Objects.equals(this.rank, classification.rank) &&
        Objects.equals(this.scientificname, classification.scientificname) &&
        Objects.equals(this.child, classification.child);
  }

  @Override
  public int hashCode() {
    return Objects.hash(IRMNG_ID, rank, scientificname, child);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Classification {\n");
    
    sb.append("    IRMNG_ID: ").append(toIndentedString(IRMNG_ID)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    scientificname: ").append(toIndentedString(scientificname)).append("\n");
    sb.append("    child: ").append(toIndentedString(child)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
